[workspace]

members = [
    "day12",
    "day11",
    "day10",
    "day9",
    "day8",
    "day7",
    "day6",
    "day5",
    "day4",
    "day3",
    "day2",
    "day1",
    "script",
    "shared"
]
